# Generated by Django 3.2.15 on 2022-09-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220924_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blade',
            field=models.CharField(choices=[('Maru Steel', (('T10 steel', 'T10 steel'), ('1095 steel', '1095 steel'), ('Manganese steel', 'Manganese steel'))), ('Damascus Steel', 'Damascus Steel'), ('Kobuse Forge Steel', 'Kobuse Forge Steel'), ('San-Mai Forge Steel', 'San-Mai Forge Steel')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='blade_thickness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='guard',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='handle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_of_the_blade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_of_the_handle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_with_sleeve',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='scabbard',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width_of_the_blade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
