# Generated by Django 3.2.15 on 2022-09-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220924_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blade_thickness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_of_the_blade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_of_the_handle',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_with_sleeve',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_of_the_blade',
            field=models.FloatField(null=True),
        ),
    ]
