# Generated by Django 3.2.16 on 2023-02-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_contact_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Contact Us Forms'},
        ),
    ]
